fix(travis): print istgt logs when travis timeouts (#340)
Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -46,7 +46,9 @@ script:
     - |
       if [ "${ARCH}" = "x86_64" ]; then
       sudo bash ./print_debug_info.sh &
-      travis_wait 60 sudo bash ./test_istgt.sh || travis_terminate 1;
+      ## If test takes more than 45 minutes then print tail logs in /tmp/istgt.log and terminate travis
+      ## Having 60minutes is causing travis timeout and not able to know easily which test is failed
+      travis_wait 45 sudo bash ./test_istgt.sh || ( sudo tail -500 /tmp/istgt.log && travis_terminate 1 );
       fi
     - pwd
     - ./build_image.sh
