chore(license): add license check in Travis (#345)
* This commit add license commits
* This commit updates the CONTRIBUTING.md with check license during checkin
* This commit adds license check to travis

Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -1,3 +1,17 @@
+## Copyright © 2018 The OpenEBS Authors
+## 
+## Licensed under the Apache License, Version 2.0 (the "License");
+## you may not use this file except in compliance with the License.
+## You may obtain a copy of the License at
+## 
+##     http://www.apache.org/licenses/LICENSE-2.0
+## 
+## Unless required by applicable law or agreed to in writing, software
+## distributed under the License is distributed on an "AS IS" BASIS,
+## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+## See the License for the specific language governing permissions and
+## limitations under the License.
+
 # top Makefile
 
 top_srcdir = @top_srcdir@
@@ -97,4 +111,14 @@ depend:
           (cd $$subdir; $(MAKE) $@) || exit $$?; \
 	done
 
+.PHONY: check_license
+check_license: check_license
+	echo ">> checking license header"
+	licRes=$$(for file in $$(find . -type f -regex '.*\.sh\|.*\.c\|.*\.h\|.*Docker.*' ! -path './src/config.h') ; do \
+              awk 'NR<=5' $$file | grep -Eq "(Copyright|generated|GENERATED)" || echo $$file; \
+      done); \
+      if [ -n "$${licRes}" ]; then \
+              echo "license header checking failed:"; echo "$${licRes}"; \
+              exit 1; \
+      fi
 #########################################################################
